language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  - CONSUMER_KEY=consumer_key
  - CONSUMER_SECRET=consumer_secret
  - ACCESS_TOKEN=access_token
  - ACCESS_TOKEN_SECRET=access_token_scret
